engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      guard-for-in:
        enabled: false
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.md"
exclude_paths:
  - "Gulpfile.js"
  - "jasmine/"
  - "lib/"
  - "node_modules/"
  - "protractor/"
