language: node_js
dist: trusty
node_js:
  - node
jobs:
  include:
    - stage: test
      env:
        - TEST_SUITE=unit-test
        # Commenting out e2e tests: https://github.com/angular/webdriver-manager/issues/270
        # - TEST_SUITE=e2e-test
      addons:
        firefox: latest
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      before_install:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      install:
        - npm install
      script: "gulp $TEST_SUITE"
    - stage: deploy-dev
      install:
        - npm install
      script: "gulp dist"
      after_success:
        - mv dist/ ng-dev/
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: ng-dev
        repo: angarg12/angarg12.github.io
        github_token: $GITHUB_TOKEN
